version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - ASLR
  - eteran
  - INSB
  - INSD
  - NT_PRSTATUS
  - OUTSB
  - OUTSD
  - PTRACE_PEEKDATA
  - PTRACE_POKEDATA
  - PTRACE_TRACEME
  - tgkill
  - tracee
  - vdso
ignoreWords: []
import: []
