version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - ASAN
  - ASLR
  - eteran
  - INSB
  - INSD
  - MSAN
  - NT_PRSTATUS
  - OUTSB
  - OUTSD
  - PTRACE_PEEKDATA
  - PTRACE_PEEKUSER
  - PTRACE_POKEDATA
  - PTRACE_TRACEME
  - tgkill
  - tracee
  - TSAN
  - USAN
  - vdso
  - xstate
ignoreWords: []
import: []
